// <auto-generated />
using System;
using Hung_Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hung_Models.Migrations.pdhDb
{
    [DbContext(typeof(pdhDbContext))]
    [Migration("20251110162025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hung_Models.Models.CtHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("DonGiaMua")
                        .HasColumnType("double precision");

                    b.Property<int?>("HoaDonId")
                        .HasColumnType("integer");

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("integer");

                    b.Property<int?>("SoLuongMua")
                        .HasColumnType("integer");

                    b.Property<double?>("ThanhTien")
                        .HasColumnType("double precision");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("CtHoaDons");
                });

            modelBuilder.Entity("Hung_Models.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HoTenKhachHang")
                        .HasColumnType("text");

                    b.Property<string>("MaHoaDon")
                        .HasColumnType("text");

                    b.Property<int?>("MaKhaHang")
                        .HasColumnType("integer");

                    b.Property<int?>("MaKhaHangNavigationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayHoaDon")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TongTriGia")
                        .HasColumnType("double precision");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("MaKhaHangNavigationId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("Hung_Models.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HoTenKhachHang")
                        .HasColumnType("text");

                    b.Property<string>("MaKhachHang")
                        .HasColumnType("text");

                    b.Property<string>("MaKhau")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Hung_Models.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLoai")
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .HasColumnType("text");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("Hung_Models.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("DonGia")
                        .HasColumnType("double precision");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("integer");

                    b.Property<int?>("MaLoaiNavigationId")
                        .HasColumnType("integer");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("text");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("text");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("MaLoaiNavigationId");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Hung_Models.Models.CtHoaDon", b =>
                {
                    b.HasOne("Hung_Models.Models.HoaDon", "HoaDon")
                        .WithMany("CtHoaDons")
                        .HasForeignKey("HoaDonId");

                    b.HasOne("Hung_Models.Models.SanPham", "SanPham")
                        .WithMany("CtHoaDons")
                        .HasForeignKey("SanPhamId");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Hung_Models.Models.HoaDon", b =>
                {
                    b.HasOne("Hung_Models.Models.KhachHang", "MaKhaHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhaHangNavigationId");

                    b.Navigation("MaKhaHangNavigation");
                });

            modelBuilder.Entity("Hung_Models.Models.SanPham", b =>
                {
                    b.HasOne("Hung_Models.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoaiNavigationId");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("Hung_Models.Models.HoaDon", b =>
                {
                    b.Navigation("CtHoaDons");
                });

            modelBuilder.Entity("Hung_Models.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Hung_Models.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Hung_Models.Models.SanPham", b =>
                {
                    b.Navigation("CtHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
